class PinkyMudhol{
	public static void main(String[] args){
		String word="hello word";
		System.out.println(word);
		String apple="i already eaten";
		System.out.println(apple);
		String ball="we will play";
		System.out.println(ball);
		String cat="its too cute";
		System.out.println(cat);
		String canada="its a wonderful place";
		System.out.println(canada);
		String camel="its neck is tall";
		System.out.println(camel);
		String animal="its a movie name";
		System.out.println(animal);
		String aunt="its a small animal";
		System.out.println(aunt);
		String bat="helps to play the cricket";
		System.out.println(bat);
		String banana="its a fruit";
		System.out.println(banana);
		String dog="it will gives a security ";
		System.out.println(dog);
		String diet="helps to body";
		System.out.println(diet);
		String drama="i iove korean drama";
		System.out.println(drama);
		String elephant="its a big animal";
		System.out.println(elephant);
		String egg="which gives hen";
		System.out.println(egg);
		String engine="vehical wants engine";
		System.out.println(engine);
		String frog="i hate frogs";
		System.out.println(frog);
		String fish="water living animal";
		System.out.println(fish);
		String front="i am watching mirror";
		System.out.println(front);
		String gate="security is there in that gate";
		System.out.println(gate);
		String goa="its a tourist place";
		System.out.println(goa);
		String gagana="ita a girl name";
		System.out.println(gagana);
		String hen="it gives egg";
		System.out.println(hen);
		String humble="this person is too humble";
		System.out.println(humble);
		String hunt="in forest hunters are there";
		System.out.println(hunt);
		String ice="its too cold";
		System.out.println(ice);
		String icecream="its too sweet";
		System.out.println(icecream);
		String iodine="its a salt";
		System.out.println(iodine);
		String jak="its a boy name";
		System.out.println(jak);
		String jelly="its a fish name";
		System.out.println(jelly);
		String jocket="in winter its too usefull";
		System.out.println(jocket);
		String kite="we will like to play";
		System.out.println(kite);
		String king="kingdom owner";
		System.out.println(king);
		String kitchen="its helps too prepare a food";
		System.out.println(kitchen);
		String lamda="its used in maths";
		System.out.println(lamda);
		String length="cloth is ";
		String girl="Trust your journey.";
		System.out.println(girl);
		String boy="Create happiness.";
		System.out.println(boy);
		String bottle="Listen more.";
		System.out.println(bottle);
		String pant="Speak kindly.";
		System.out.println(pant);
		String clip="Celebrate life.";
		System.out.println(clip);
		String teddy="Enjoy the moment.";
		System.out.println(teddy);
		String top="Keep moving forward.";
		System.out.println(top);
		String str="hello word";
		System.out.println(str);
		String test="Now is the time for all good ";
		System.out.println(test);
		String ball="men to come to the aid of their country";
		System.out.println(ball);
		String doll="Time heals ";
		System.out.println(doll);
		String brush="Love conquers.";
		System.out.println(brush);
		String jug="Dream big.";
		System.out.println(jug);
		String laptop="Stay strong.";
		System.out.println(laptop);
		String bag="Be kind.";
		System.out.println(bag);
		String dog="Chase joy";
		System.out.println(dog);
		String pen="Learn daily";
		System.out.println(pen);
		String mobile="Forgive often.";
		System.out.println(mobile);
		String sky="Believe in yourself.";
		System.out.println(sky);
		String kite="Find your passion.";
		System.out.println(kite);	
		String blue="Seek adventure.";
		System.out.println(blue);
		String girl="Trust your journey.";
		System.out.println(girl);
		String boy="Create happiness.";
		System.out.println(boy);
		String bottle="Listen more.";
		System.out.println(bottle);
		String pant="Speak kindly.";
		System.out.println(pant);
		String clip="Celebrate life.";
		System.out.println(clip);
		String bed="Practice gratitude.";
		System.out.println(bed);
		String plate="Discover inner peace.";
		System.out.println(plate);
		String city="Inspire others.";
		System.out.println(city);		
		String ring="Count your blessings.";
		System.out.println(ring);
		String soap="Choose happiness.";
		System.out.println(soap);	
		String comb="Stay focused.";
		System.out.println(comb);
		String greating="goodmorning.";
		System.out.println(greating);	
		String comb="Stay focused.";
		System.out.println(comb);	
		String crowd="in marcket lot of people are there";
		System.out.println(crowd);
		String vehical="i love to drive";
     	System.out.println(vehicle);
		String zibra="which indicates crossing a roadline";
		System.out.println(zibra);
		string mango="ita a seasonal fruit";
		System.out.println(mango);
		String laptop="we usethis";
		System.out.println(laptop);
		String bag="we will put our books";
		System.out.println(bag);
		
		} 
}