class Mall
{
	public static void ()
	{
	String starbucks="Coffee";
	String chaiwala="tea";
	System.out.println(starbucks+chaiwala);
	boolean takeAway=true;
	boolean dineIn=false;
	boolean koffee=starbucks==chaiwala;
	System.out.println("koffee :"+koffee);
	
	}
	public static void dairy()
	{
		double priceOfDairy=349.99;
		char authorInitial='H';
		priceOfDairy=333.33; //re-assign
		System.out.println(priceOfDairy);
		System.out.println(authorInitial);
		
	}
	public static void karnataka()
	{
		String sharavat="PAVAN";
		int sharmaScore=40;
		System.out.println(sharavat + sharavatScore);
		String pande="VIKAS";
		int pandeScore=38;
		System.out.println(vikas + vikasScore);
		String narval="SANDEEP";
		int narvalScore=29;
		System.out.println(narval + narvalScore);
		String huda="Deepak";
		int hudaScore=30;
		System.out.println(huda + hudaScore);
		String sangva="ASHISH";
		int sangvaScore=18;
		System.out.println(sangva + sangvaScore);
		String narval="Manjunath";
		int narvalScore=12;
		System.out.println(narval + narvalScore);
		String kong="kING";
		int kongScore=4;
		System.out.println(kong + kongScore);
		String narval="PRADEEP";
		int narvalScore=0;
		System.out.println(narval + narvalScore);
		
	}
	public static void mumbai()
	{
		String maruti="GIRISH";
		int marutiScore=42;
		System.out.println(maruti + marutiScore);
		String singh="MAHINDHAR";
		int singhScore=28;
		System.out.println(singh + singhScore);
		String singh="SURINDHAR";
		int singhScore=34;
		System.out.println(singh + singhScore);
		String singh="GUMAN";
		int singhScore=22;
		System.out.println(singh+ singhScore);
		String jai="BHAGWAN";
		int jaiScore=16;
		System.out.println(jai + jaiScore);
		String rane="PRANAY";
		int raneScore=15;
		System.out.println(rane + raneScore);
		String jansen="MARCO";
		int jansenScore=8;
		System.out.println(jansen + jansenScore);
		String rabada="KAGISO";
		int rabadaScore=4;
		System.out.println(rabada + rabadaScore);
		String maharaj="KESHAV";
		int maharajScore=0;
		System.out.println(NARVAL + NARVALScore);
		
	}
	
	public static void main(String[] args)
	{
		starbucks();
		dairy();
		karnataka();
		mumbai();
	}
}